### ISSUE TITLE
Exercise and ambient mode

### ISSUE THREAD

**Issue by Secretbox1987** [android/health-samples#34]
I start the exercise, after a while it goes into ambient mode and the data starts coming in once a minute.  i added an alarm manager and wake up the app every 5 seconds, but the health service still returns the data 1 time per minute

**Comment by ithinkihaveacat** [comment]
This is the expected behavior: to preserve power, health services will deliver data in batches, see [Work with data from ExerciseClient](https://developer.android.com/training/wearables/health-services/active#work-with-data). (The exact rate and behaviour depends on the hardware.)

So even if your app itself is woken up every 5 seconds, health services will not deliver data at that frequency. What is your use case? For most data types you should receive multiple data points within each batch—the sensors are _recording_ data at a higher rate than the rate at which it is delivered by health services—which should be sufficient if ambient mode is active.
