### ISSUE TITLE
`startActivityForResult` is not working if called via Flutter Method Channels

### ISSUE THREAD

**Issue by rutulchauhan** [android/health-samples#50]
Hi. I trying to integrate the health-connect sdk in my flutter app, but while trying to navigate user to grant permission from the Health Connect app via `startActivityForResult` as suggested in your demo app, is not working & wouldn't open the Health app.

Attaching my code for reference,

```
     val healthConnectClient = HealthConnectClient.getOrCreate(activity!!.applicationContext)
        val permissionList = callToHealthConnectTypes(call)
        val intent = healthConnectClient.permissionController.createRequestPermissionActivityContract()
            .createIntent(activity!!.applicationContext, permissionList)
        activity!!.startActivityForResult(intent,1111)
```        

Any idea to fix it or approximate deadlines for delivering a flutter plugin for the same?

**Comment by breanatate** [comment]
Hi,

Thanks for reaching out.

I'm not very familiar with Flutter, but from looking through the Flutter docs, it seems there is [an equivalent to startActivityForResult](https://docs.flutter.dev/get-started/flutter-for/android-devs#what-is-the-equivalent-of-startactivityforresult).

If this does not solve the issue, please follow up and let us know.

**Comment by rutulchauhan** [comment]
Hi, @breanatate 

We don't have any issues on the flutter end. But we are trying to startActivity from Android native code as described above.
Which is not opening the HealthConnect permission screen.

Let me know if you have references for the same.

**Comment by breanatate** [comment]
Hi,

It might be best to follow the permissions flow outlined [here](https://developer.android.com/guide/health-and-fitness/health-connect/get-started#step_4_declare_and_request_permissions) in the documentation. 

Our demo app uses [Jetpack Compose](https://developer.android.com/jetpack/compose), which is why the demo app doesn't use startActivityForResult directly, but [rememberLauncherForActivityResult](https://developer.android.com/reference/kotlin/androidx/activity/compose/package-summary#rememberLauncherForActivityResult(androidx.activity.result.contract.ActivityResultContract,kotlin.Function1)) instead. If you are able to use Compose and Flutter, I would definitely recommend that since you would be able to replicate the sample more closely.

**Comment by rutulchauhan** [comment]
Hi @breanatate thanks for the suggestions. Though is it possible to ask for permissions in HealthConnect without using JetpackCompose? Due to some reason, we are not able to add Compose at the moment.  To be precise we are getting all the data from HealthConnect (if we manually provide permissions from the app) we are just unable to display `permission screen of HealthConnect.

**Comment by breanatate** [comment]
The [documentation](https://developer.android.com/guide/health-and-fitness/health-connect/get-started#step_4_declare_and_request_permissions) linked above does not use Compose. It's difficult to understand without a bit more code from your app, but you should be able to use the steps outlined there to launch permissions for the first time. It outlines creating the permissions launcher, as well as the logic for entering or avoiding the launcher depending on granted permissions.

If this does not work, I am also attaching a snippet that should enable you to launch the Health Connect settings from your app (using an intent):

`val intent =
  context.packageManager.getLaunchIntentForPackage("com.google.android.apps.healthdata")
if (HealthConnectClient.isAvailable(context) && intent !== null) {
  context.startActivity(intent)
}
`

**Comment by kelfin91** [comment]
?
