### ISSUE TITLE
ExerciseUpdateCallback is not triggered when wear is dim

### ISSUE THREAD

**Issue by votheanh39** [android/health-samples#77]
I need to collect the latest health data from `exerciseClient` to send back to the phone. But it seems the `ExerciseUpdateCallback`  is not triggered when the wear is dim ( I tested on latest build of Exercises Sample project ). How can I make it work, thanks

**Comment by CoreFloDev** [comment]
I got the same issue, but if you go running with the app you will see that it triggers call back but very randomly like once every minute or 30 seconds. My guess is that they never test their sdk on real device only with emulator and they have made their sdk follow the ambient lifecycle.

**Comment by breanatate** [comment]
The processor only delivers ExerciseUpdates when the device is awake or when the maximum reporting period is reached. Data will be still delivered when the screen is dim (but much less frequently than when the screen is awake), and once the user looks at the screen, the latest data is immediately delivered. You can read more [here](https://developer.android.com/training/wearables/health-services/active#work-with-data).

**Comment by CoreFloDev** [comment]
How are we supposed to do that then? https://developer.android.com/training/wearables/health-services/active#store-and-upload

**Comment by breanatate** [comment]
Hi @CoreFloDev can you expand on your question? Currently the data delivery frequency while the screen is dim varies by device (and, for example, can be up to 150 seconds). What's the use case you're trying to solve? That way we can see if there's an existing recommended solution or one that can be proposed.

**Comment by CoreFloDev** [comment]
ok to be clear, the documentation state that:

> Store and upload data
> Use [Room](https://developer.android.com/training/data-storage/room) to `persist data delivered from Health Services`. Data upload should happen at the end of the exercise using a mechanism like [Work Manager](https://developer.android.com/topic/libraries/architecture/workmanager). This will ensure that network calls to upload data are deferred until the exercise is over, minimizing power consumption during the exercise and simplifying the work the service does.

But in order to persist data from health service, you kind of need to get it first right? So my question is how are you supposed to get the data knowing that `ExerciceUpdate` doesn't emit if the screen dim? Are we supposed to display to the user only his data when the screen wasn't dim. Maybe there is an other that isn't documented to get it?

**Comment by CoreFloDev** [comment]
If you do more research on GitHub, you can find that repository https://github.com/garanj/tempo from I think one of your team. And there is the exact same mistake into it, it uses `exerciseUpdate` to save the current data but as mentioned earlier that's not correct as the data will be updated only maybe every 150 seconds.

I don't see how to fix that issue, for me that's an architectural mistake that makes `health-services` not usable in production

**Comment by breanatate** [comment]
Can you provide more information on the use case you're solving? That would help us determine if there is a recommended solution for the scenario.

If the data needs to be uploaded continuously throughout the workout and in short intervals (i.e. sending it back to the phone periodically like @votheanh39 mentioned) the screen would probably need to be kept awake, with the caveat that this can impact the battery life. We are sharing this scenario back with the team to see if there is a better way to solve for this and if there is a change to the API that could be proposed.

Although the `ExerciseUpdate` messages are sent less frequently when the screen is dim, the data that is delivered is ultimately the same--it's still sampled at the same frequency. When the screen is active/not dim, the app receives updates every second or few seconds so that the app can render up-to-date metrics on screen (for example). If the device then happens to dim/enter ambient mode any data in the process of being batched is delivered when the screen exits ambient mode or reaches the maximum reporting period--no data from the workout is lost, the delivery was just delayed.

**Comment by CoreFloDev** [comment]
Ah ok I see, thanks you @breanatate

**Comment by nolza95** [comment]
so far, healthservices.exerciseClient isn't suitable for app which would handle message(HR, LOCATIONS..) every 5s or 10s, is it?
and then, What would you recommend to create an app that receives and uses messages once every 10 seconds?
